name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          npm install -g cy2
          npm install
      - name: Setup Aplication under test
        run: docker-compose -f ExpenseWeb/docker-compose.yml up -d
      - name: Setup Sorry Cypress
        run: docker-compose up -d
      - name: E2E parallel Test
        run: CYPRESS_API_URL="http://localhost:1234" cy2 run  --parallel --record --key abcdef --ci-build-id hello-cypress    
      - name: Cypress E2E Test
        uses: cypress-io/github-action@v2.9.12
        with:
          spec: cypress/integration/tests/expenseWeb.spec.js