name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
          
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'    

      - name: Install dependencies
        run: |
          npm install -g cy2
          npm install

      - name: Setup Aplication under test
        run: docker-compose -f ExpenseWeb/docker-compose.yml up -d

      - name: Setup Sorry Cypress Environment
        run: docker-compose up -d

      - name: E2E parallel Test
        run: CYPRESS_API_URL="http://localhost:1234" cy2 run  --parallel --record --key abcdef --ci-build-id hello-cypress
        continue-on-error: true

      - name: E2E Api Test
        run: npm run api:test  
        continue-on-error: true
        
      - name: E2E Performance test
        uses: k6io/action@v0.2.0
        with:
          filename: performance/perf_login.js