name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          npm install
      - name: Setup Aplication under test
        run: docker-compose -f ExpenseWeb/docker-compose.yml up -d
      - name: Cypress E2E Test
        uses: cypress-io/github-action@v2.9.12
        with:
          spec: cypress/integration/tests/expenseWeb.spec.js