name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node14.16.0-chrome90-ff88

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          npm install
      - name: Setup Aplication under test
        run: docker-compose -f ExpenseWeb\docker-compose.yml up -d
      - name: Cypress E2E Test
        uses: cypress-io/github-action@v2.9.12
        with:
          spec: cypress/integration/tests/expenseWeb.spec.js